import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Providers from "@/contexts/Providers";
import { configApp } from "@/helper/constants";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Muebleria Luxe",
  description: "Generated by Muebleria Luxe",
  icons: {
    icon: `${configApp.logo}.ico`,
    shortcut: `${configApp.logo}.ico`,
    apple: `${configApp.logo}.ico`,
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
